version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: retail
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_ui
    ports:
      - "8080:8080"
