name: "retail_dbt"
version: "1.0"
config-version: 2
profile: "retail"
model-paths: ["models"]

models:
  retail_dbt:
    +materialized: view
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
