services:
  airflow-db:
    image: postgres:14.12
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      retries: 10

  airflow:
    image: apache/airflow:2.9.3
    depends_on:
      airflow-db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow"
      _AIRFLOW_WWW_USER_USERNAME: "admin"
      _AIRFLOW_WWW_USER_PASSWORD: "admin"
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create
          --role Admin
          --username ${_AIRFLOW_WWW_USER_USERNAME}
          --password ${_AIRFLOW_WWW_USER_PASSWORD}
          --firstname Ricky
          --lastname Admin
          --email ricky@example.com || true &&
        airflow webserver & airflow scheduler
      "
    ports:
      - "8081:8080" # Airflow UI (Adminer is on 8080)
    volumes:
      - ../:/opt/airflow/repo # mount your whole repo
      - ./dags:/opt/airflow/dags # your DAGs
    restart: unless-stopped

volumes:
  airflow_db_data:
